DROP TABLE IF EXISTS RESOURCE_LOCK;
CREATE TABLE RESOURCE_LOCK(
    ID                       BIGINT         AUTO_INCREMENT,
    LOCK_KEY                 VARCHAR(64)    NOT NULL,
    LOCK_NAME                VARCHAR(64)    NOT NULL,
    UPDATE_TIME              TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    EXPIRED_TIME             TIMESTAMP      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UIDX_LOCK_KEY UNIQUE (LOCK_KEY),
    PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 COLLATE=utf8_general_ci;
