DROP TABLE IF EXISTS RESOURCE_LOCK;
CREATE TABLE RESOURCE_LOCK(
    LOCK_KEY                 VARCHAR(64)    NOT NULL,
    LOCK_NAME                VARCHAR(64)    NOT NULL,
    LOCK_HOLDER              VARCHAR(64)    NOT NULL,
    UPDATE_TIME              TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    EXPIRED_TIME             TIMESTAMP      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(LOCK_KEY,LOCK_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 COLLATE=utf8_general_ci;
